config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :flits
  resources :relationships,       only: [:create, :destroy]

  get 'about' => 'static_pages#about'

  
  root to: 'static_pages#home'
end

app/models/flit.rb
class Flit < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook] #, :confirmable
  
  has_many :flits, dependent: :destroy
  validates :password, length: { minimum: 6 }
  has_attached_file :image

  has_many :flits
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
 
   def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image
      end
    end

    def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end

    def follow(other_user)
      active_relationships.create(followed_id: other_user.id)
    end
  
    def unfollow(other_user)
      active_relationships.find_by(followed_id: other_user.id).destroy
    end

    def following?(other_user)
      following.include?(other_user)
    end

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
 
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end


    
end

app/controllers/flits_controller.rb
class FlitsController < ApplicationController
  def index
    @flit = Flit.all
  end

  def show
    @flit = Flit.find(params[:id])
  end

  def new
    @flit = Flit.new
  end

  def create
    @flit = Flit.new(flit_params)
    @flit.user = current_user
      if @flit.save
        redirect_to flits_path
      else
        render 'static_pages/home'
      end
  end

  def destroy
    @flit = Flit.find(params[:id])

    if @flit.destroy
       redirect_to @flit
     else
       render root_url
     end
  end

  private

  def flit_params
    params.require(:flit).permit(:content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def home
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!

  def index
    @users = User.all
  end

  def create
    @user = User.create( user_params )
  end

  def show
    @user = User.find(params[:id])
    @flits = @user.flits.paginate(page: params[:page])
  end
  
  def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       render "devise/registrations/edit"
     end
   end

   def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

private
  
  def user_params
    params.require(:user).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flits_helper.rb
module FlitsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flits/_flits.html.erb
<%= form_for(@flit) do |f| %>
  <% if @flit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flit.errors.count, "error") %> prohibited this flit from being saved:</h2>

      <ul>
      <% @flit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, placeholder: "Enter new flit..." %>
  </div>

  <div class="actions">
    <%= f.submit "Post", class: "btn btn-purple" %>
  </div>
<% end %>

app/views/flits/index.html.erb
<h1>Flutter Stream <%= form_tag flits_path, :method => 'get' do %>
<% end %>
</h1>

<table>
<% @flit.each do |flit| %> 
  <tr>
    <td><%= flit.content %></td>
    <td><%= link_to 'Delete', flit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br/>

<%= link_to 'New Flit', new_flit_path %>

app/views/flits/new.html.erb
<h1>New Flit</h1>

<%= render 'flits' %>

<%= link_to 'Back', flits_path %>

app/views/flits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h3>Content:</h3>
  <%= @flit.content %>
</p>

<%= link_to 'Back', flits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flutter </title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <header class="nav nav-tabs">
      <div class="container">
        <nav>  
          <ul class="nav nav-tabs">
            <li><%= link_to 'Home', root_path %></li>  
            <li><%= link_to 'Flutter Stream', flits_path %></li>  
            <li><%= link_to 'About', about_path %></li>

              <div class="pull-right user-info">
                <% if current_user %>
                Hello <%= link_to (current_user.name ||current_user.email),edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                <div align = "center"><%= image_tag(current_user.image)%></div> <br>
                <% else %>
                <%= link_to "Sign In", new_user_session_path %> or
                <%= link_to "Sign Up", new_user_registration_path %>
                <% end %>
              </div>
          </ul>
        </nav>
      </div>
    </header>

  </head>
  <body>
  
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : 'your-app-id',
          xfbml      : true,
          version    : 'v2.1'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
  
    <div class="container">

      <%= yield %>
    </div>


    <footer id="footer" align="center">
      <em>
        Copyright &copy; 2015 FreeSpirit Development
      </em>
    </footer>

  </body>
</html>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/static_pages/about.html.erb
<h1>About Flutter</h1>

<p>Flutter a Twitter clone</p>

app/views/static_pages/home.html.erb
<div class="jumbotron" id="home">
  <div id="content">
  <h1>
    <span style="color: #b19cd9;">Flutter</span>
  </h1>
  <h4 align="center">Twitter Clone!</h4>
  <p align="center">
    <%- if user_signed_in? %>

      <%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-purple :hover'  %>
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-purple :hover' %>
    <% end %>
  </p>
  </div>
   <section class="stats">
        <%= render 'shared/stats' %>
      </section>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_u.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-purple" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-purple" %>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <%= link_to user.name, user %><br>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>User Details</h1>

  <table style="width=100%">
    <tr>
      <td><%= @user.name %></td> 
      <td><%= @user.email %></td>
  </tr>
  </table>
  <section class="stats">
    <%= render 'shared/stats' %>
  </section>

  <div>
    <%= render 'follow_form' %>
    <% if @user.flits.any? %>
      <h3>Flits (<%= @user.flits.count %>)</h3>
      <ol>
        <%= render @flits %>
      </ol>
      <%= will_paginate @flits %>
    <% end %>
  </div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Flits:</b> <%= @user.flits.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        
          <% @users.each do |user| %>
            <%= link_to user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>